
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: student-service

  datasource:
    url: jdbc:postgresql://localhost:5432/studentdb
    username: postgres
    password: 8599
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
